  <?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic|Bitter:700');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
$banner = $this->themeSettingAssetUrl('banner');
$bannerWidth = ($this->themeSetting('banner_width')) ? $this->themeSetting('banner_width') : '';
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_','-', $this->themeSetting('banner_position')) : 'center';
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php if ($this->themeSetting('accent_color') !== '' || $this->themeSetting('nav_color') !== ''): ?>
        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a {
                color: <?php echo $accentColor; ?>
	    } 
            input[type="submit"]:hover,
            button:hover,
            .button:hover,
            .sub-menu a:hover,
            .site-page-pagination a:hover,
            a.advanced-search:hover {
                background-color: <?php echo $accentColor; ?>
            }
            <?php endif; ?>

            <?php if ($navColor = $this->themeSetting('nav_color')): ?>
            .oc-menu {
                background-color: <?php echo $navColor; ?>
            }
            <?php endif; ?>

            .banner {
                height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
                align-items: <?php echo $bannerPosition; ?>;
            }
            <?php if ($bannerHeightMobile !== ''): ?>
                @media screen and (max-width:640px) {
                    .banner {
                        height: <?php echo $bannerHeightMobile; ?>;
                    }
                }
	    <?php endif; ?>i
	    

	/*CST-Logan*/
	footer{
		background: #000 !important; 
	}
	
	/*end CST-Logan*/
        </style>
        <?php endif; ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <div id="oc-container" class="oc-container">
            <div class="oc-pusher">
                <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
                <?php echo $userBar; ?>
                <header class="site-header">
                    <h1>
                        <a href="<?php echo $site->url(); ?>" class="site-title">
                        <?php if ($this->themeSetting('logo')): ?>
                            <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                        <?php else: ?>
                            <?php echo $escape($siteTitle); ?>
                        <?php endif; ?>
                        </a>
                    </h1>
                    <?php echo $this->partial('common/search-form'); ?>
                    <div id="oc-trigger">
                        <button id="menu-button" class="o-icon-menu" data-effect="oc-push" aria-label="<?php echo $this->translate('Menu'); ?>"></button>
                    </div>
                    <nav id="menu" class="oc-menu oc-push" role="navigation">
                        <?php echo $site->publicNav()->menu()->renderMenu(); ?>
                    </nav>
                </header>

                <main class="oc-content" role="main">
                  <div class="oc-content-inner">
                    <?php if ($banner): ?>
                    <div class="banner <?php echo $bannerWidth; ?>">
                        <img src="<?php echo $this->themeSettingAssetUrl('banner'); ?>" title="Banner">
                    </div>
                    <?php endif; ?>
                    <div id="content" role="main">
                      <?php echo $this->content; ?>
		    </div>
		    
		    <footer>
		       <div class="sub-footer">
				<div class="footer-branding-logo">
					 <a class="sub-logo" href="http://<?php echo $_SERVER['SERVER_NAME'];?>/omeka-s/s/oswego-transcribe/page/welcome"><img src="http://<?php echo $_SERVER['SERVER_NAME'];?>/omeka-s/files/images/logos/new-logo-white.jpg" alt="Oswego Transcribe"></a>	
				</div>
				<div class="footer-branding">
					<a href="#"> Contact us </a>
					<a href="https://www.oswego.edu/library/"> SUNY Oswego Library </a>
					<a href="https://www.oswego.edu/library/archives-special-collections"> SUNY Oswego Archives and Collections  </a>
				</div>
		       </div>

		    <div class="info-wrapper">
			<div class="info-copyrights">
				<?php if ($footerContent = $this->themeSetting('footer')): ?>
                        	<?php echo $footerContent; ?>
                        	<?php else: ?>
                        	    <?php echo $this->translate('Powered by Omeka S'); ?>
				<?php endif; ?>
			</div>
			<div class="info-social">
				<a class="footer-fb" href="https://www.facebook.com/SUNYOswego/"><img src="http://<?php echo $_SERVER['SERVER_NAME'];?>/omeka-s/files/images/icons/fb-24.png" alt="Footer FB"></a>	
				<a class="footer-ig" href="https://www.instagram.com/sunyoswego/"><img src="http://<?php echo $_SERVER['SERVER_NAME'];?>/omeka-s/files/images/icons/ig-24.png" alt="Footer IG"></a>	
				<a class="footer-tt" href="https://www.twitter.com/sunyoswego/"><img src="http://<?php echo $_SERVER['SERVER_NAME'];?>/omeka-s/files/images/icons/tt-24.png" alt="Footer TT"></a>	
				<a class="footer-yt" href="https://www.youtube.com/user/sunyoswegovideo"><img src="http://<?php echo $_SERVER['SERVER_NAME'];?>/omeka-s/files/images/icons/yt-24.png" alt="Footer YT"></a>	

			</div>
			
		    </div>
                    </footer>
                  </div>
                </main>
            </div>
        </div>
        <script type="text/javascript" src="<?php echo $this->assetUrl('js/offcanvas.js'); ?>"></script>
    </body>
</html>
